
spring.application.name=BRISA-BACKEND
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/brisa
spring.datasource.username=postgres
spring.datasource.password=130680
spring.datasource.driver-class-name=org.postgresql.Driver

backend.url=http://localhost:8082
frontend.url=http://localhost:4300

# Configuração JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Configuração de upload de arquivos para arquivos grandes (até 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

api.security.token.secret=${JWT_SECRET:my-secret-key}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=

